import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <meta property="twitter:title" content="VideoEmberReact"></meta>
      <meta
        property="twitter:description"
        content="サービスを選択してIdを入力するだけで動画をサービスから埋め込めます"
      ></meta>
      <meta property="og:title" content="VideoEmberReact"></meta>
      <meta
        property="og:description"
        content="サービスを選択してIdを入力するだけで動画をサービスから埋め込めます"
      />
      <meta property="og:url" content="https://kobakoo.com"></meta>
      <body>{children}</body>
    </html>
  );
}
